---
- name: "Checkpoint VNF Bootstrap playbook"
  hosts: localhost
  gather_facts: no


  tasks:
    - name: "Load input data"
      include_vars:
        dir: vars
        name: data
        ignore_unknown_extensions: true

    - name: "Validating if user IPs are Valid"
      assert:
        that: item is ansible.utils.ipv4_address
        fail_msg: '{{item}} is not a valid IP address'
        quiet: true
      loop: "{{ data['interfaces'] | map(attribute='ipv4-address') | select() + data['ha'] | map(attribute='ipv4-address') | select() + data['wan'] | map(attribute='ipv4-address') | select() + data['vlan'] | map(attribute='ipv4-address') | select() + data['mgmt'] | map(attribute='ipv4-address') | select()}}"


    - name: "Validating if Netmask is Valid"
      assert:
        that: item is ansible.utils.ipv4_netmask
        fail_msg: '{{item}} is not a valid Netmask'
        quiet: true
      loop: "{{ data['interfaces'] | map(attribute='subnet-mask') | select() + data['ha'] | map(attribute='subnet-mask') | select() + data['wan'] | map(attribute='subnet-mask') | select() + data['vlan'] | map(attribute='subnet-mask') | select() + data['mgmt'] | map(attribute='subnet-mask') | select()}}"


    - name: "Checking if LAN2 is configured"
      fail:
        msg: Cancelling the Playbook. Please review if LAN2 interface is defined
      when: data['interfaces'] | selectattr('name','match','LAN2') | length == 0

    - name: "Render interfaces config"
      ansible.builtin.template:
        src: templates/interfaces.j2
        dest: rendered/interfaces.cfg
        lstrip_blocks: yes
      when:
      - data['interfaces'] is defined

    - name: "Validating System information"
      assert:
        that:
          - data['system'] is defined
          - data['system']['central_management']['address'] is ansible.utils.ipv4_address
          - data['system']['config_type'] == 'primary' or data['system']['config_type'] == 'secondary'
          - data['interfaces'] | selectattr('name','eq','LAN2') | map(attribute='gateway') | join is ansible.utils.ipv4_address
        fail_msg: "Input Data ==> {{data['system']}}"
        quiet: true

    - name: "Render System config"
      ansible.builtin.template:
        src: templates/system.j2
        dest: rendered/system.cfg
        lstrip_blocks: yes

    - name: "Checking pre-requisite to prepare LAN route config [if LAN1 gateway is configured]"
      assert:
        that:
          - data['interfaces'] | selectattr('name','eq','LAN1') | map(attribute='gateway') | select() | length > 0
          - data['interfaces'] | selectattr('name','eq','LAN1') | map(attribute='gateway') | join is ansible.utils.ipv4_address
        fail_msg: "Either LAN1 gateway is not configured or its not a Valid IP address"
        quiet: true
      when: lookup('file', 'vars/lan-routes').splitlines() | list | length > 0

    - name: "Validating Destination networks in lan-routes file, if present"
      assert:
        that:
          - item is ansible.utils.ipv4
        fail_msg: "{{item}} is not a Valid IP address"
        quiet: true
      loop: "{{lookup('file', 'vars/lan-routes').splitlines() | list}}"
      when: lookup('file', 'vars/lan-routes').splitlines() | list | length > 0


    - name: "Render Lan routes config"
      ansible.builtin.template:
        src: templates/lan-routes.j2
        dest: rendered/lan-routes.cfg
        lstrip_blocks: yes
      failed_when: data['interfaces'] | selectattr('name','eq','LAN1') | map(attribute='gateway') | select() | length == 0

    - name: "Render ANAP to VNF BGP config"
      ansible.builtin.template:
        src: templates/lan2-bgp.j2
        dest: rendered/lan2-bgp.cfg
        lstrip_blocks: yes
      when: data['system']['bgp_asn'] != "" and data['system']['bgp_asn'] != "56278" and data['system']['bgp_asn'] | int < 65535

    - name: "Creating base test file"
      ansible.builtin.lineinfile:
        path: output/user-data
        create: yes
        line: "#!/bin/bash"

    - name: "Creating userdata file for bootstrap config"
      ansible.builtin.lineinfile:
        path: output/user-data
        insertafter: EOF
        line: "clish -c '{{item}}'"
      with_lines: cat rendered/*.cfg
      when: item != ""

    - name: "Creating file with all commands[Backup for manual fw config]"
      ansible.builtin.lineinfile:
        path: output/command-set.txt
        insertafter: EOF
        create: yes
        line: "{{item}}"
      with_lines: cat rendered/*.cfg
      when: item != ""

    - name: "Creating cloud-init bootstrap image"
      ansible.builtin.command: mkisofs -output output/configdrive.iso -volid cidata -joliet -V config-2 -rock output/user-data
      notify: result

  handlers:
    - name: result
      debug:
        msg: "Bootstrap cloud-init .iso image and Backup command-set file can be download from output directory"

